evm_bench: ## Run Evm Circuit benchmarks
	@cargo test --profile bench bench_evm_circuit_prover_halo2ecc --features benches  -- --nocapture

evm_bench_mock: ## Run Evm Circuit benchmarks
	@cargo test --profile bench bench_mock_evm_circuit_prover_halo2ecc --features benches  -- --nocapture
